### ISSUE TITLE
[Question] Updating Hosted Seraph

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#22]
when seraph updates how do I update my hosted seraph

**Comment by a456pur** [comment]
hey there!! i'm making a new tutorial to use forking instead of the template repository, but i'll explain it here

to fork you click the fork button, choose a name and click create, then at the top of the repository you'll see this
<img width="915" alt="image" src="https://github.com/a456pur/seraph/assets/77299925/3ec5a6d6-2326-4434-bf3a-ba8e10df268b">

if it says you are a commit behind, then that means your version of seraph is outdated! you can then click 'Sync fork' and then update branch
<img width="915" alt="image" src="https://github.com/a456pur/seraph/assets/77299925/ef3ad1cf-b33e-4828-b3fe-01b1862238f3">

github pages will then see this and refresh it (may take around 15 minutes to upload)

hope this helps, more will be clarified in the updated tutorial

**Comment by Heheheha12345678** [comment]
Thank you and thank you for making Seraph it is a really great website
