### ISSUE TITLE
[Suggestion] Proxy

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#35]
**suggestion**
a proxy to unblock other websites.

**Comment by a456pur** [comment]
i have considered this but i'm probably not going to implement a proxy
due to how hosting works for us a proxy would be even more expensive to run and i'm already paying for this site out of pocket

if you are looking for a good proxy to use, i recommend using [interstellar](https://github.com/InterstellarNetwork/Interstellar)! you can join their discord and get links or even host your own, it works really well as well! give them a star if you like it as well, it really is an amazing tool :)

**Comment by Igenoxnosr** [comment]
> i have considered this but i'm probably not going to implement a proxy; due to how hosting works for me a proxy would be even more expensive to run and i'm already paying for this site out of pocket
> 
> if you are looking for a good proxy to use, i recommend using [interstellar](https://github.com/InterstellarNetwork/Interstellar)! you can join their discord and get links or even host your own, it works really well as well! give them a star if you like it as well, it really is an amazing tool :)

hey a456pur you can unblock any website by doing cdn and entering a host link that goes to a proxy or doesnt on fastly. fastly is free and I find it funny that you can unblock almost anything with it. its not a promotional thing but you could create the link and than do a full screen embed on the website for free
